### ISSUE TITLE
LDMud LPC compatible?

### ISSUE THREAD

**Issue by MTester2** [GwennKoi/vscode-lpc-lang#1]
Hi,
How compatible/in-sync is this with the LDMud (post LP) driver?  I know you are updating with Fluff in mind, which is based off of MudOS...  If I want one more suitable to LDMud (which is based off LPMud/Amylaar, not MudOS), would it make more sense to do my own starting with your Pike version?  I'm not sure, but it seems like Pike might be even more out of date in terms of compatibility with LDMud?

**Comment by GwennKoi** [comment]
Not entirely sure on that. I've only developed in the MudOS branch.

**Comment by MTester2** [comment]
Ok.  I went ahead and forked off of this repo so I can tailor to LDmud style.
