### ISSUE TITLE
Possible problem with the regex finding keywords in string literals

### ISSUE THREAD

**Issue by gesslar** [GwennKoi/vscode-lpc-lang#18]
The regex is detecting keywords in the middle of a string literal.

For example, finding `for` in the middle of the string literal in the accompanied screenshot.
![image](https://user-images.githubusercontent.com/1266935/170805284-c7ac7e4a-8066-4748-a6d4-0ad1251435f2.png)

**Comment by michaelprograms** [comment]
I too am also noticing keywords inside of string literals, and it seems that the colored highlighting of the string literal is missing as well. I believe it used to highlight in orange, although I could be mistaken.
![image](https://user-images.githubusercontent.com/1260602/170837473-b770b15d-b3ae-4309-9100-87260a88c307.png)

**Comment by GwennKoi** [comment]
Fixed.
