### ISSUE TITLE
@ and @@ text formatting shortcuts end too soon.

### ISSUE THREAD

**Issue by jlchmura** [GwennKoi/vscode-lpc-lang#24]
Copying from @gesslar's issue report here https://github.com/jlchmura/prettier-lpc-vscode/issues/18
```	       
set("long", @text

   The soft, black and white pelt has been expertly cured to preserve the 
texture and hairs of the panda's fur. Though the skin is quite beautiful,
the animal itself must have been even more majestic.

text
);
```

When the marker (in this case `text`) appears in another word at the start of a line (`texture` on the 4th line), the highlighting ends there instead of at the actual end marker.

![screenshot attached](/assets/8180397/9c9de63c-e514-4c99-959d-543bc6bf1cb6)

**Comment by gesslar** [comment]
Please test this PR: https://github.com/GwennKoi/vscode-lpc-lang/pull/25
